name: Upload Python Package connect4_robot_j4 to PyPI

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: pypi

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install build
        run: pip install build

      - name: Build the package
        run: python -m build python/j4_connect4

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: python/j4_connect4/dist
          password: ${{ secrets.PYPI_API_TOKEN }}